### ISSUE TITLE
Failure of setup due to missing dependencies.

### ISSUE THREAD

**Issue by srbcheema1** [srbcheema1/medipack#3]
There is a bug in setup.py that makes it difficult to install on systems without full dependencies installed before running the setup.
the main reason is the importing of the `from medipack.main import dependency_map`.
due to this line the main.py file is being loaded which is dependent on these dependencies and causing problem. so we should not import anything buggy( or something that can cause breakage especially crsh or exit()) in `setup.py`

**Comment by srbcheema2** [comment]
![medipack_setup_failure_ubuntu](https://user-images.githubusercontent.com/20281408/46319472-ce16e100-c5f7-11e8-80b5-53559e8c97b1.jpeg)
![medipack_setup_failure_fedora](https://user-images.githubusercontent.com/20281408/46319480-d3742b80-c5f7-11e8-8fd4-f518c6e5602e.jpeg)

**Comment by srbcheema2** [comment]
there were the bugs that were faced during the installation of medipack due to missing dependencies.
This isuue is solved now by improving the structure of setup.py
