### ISSUE TITLE
calling medipack with no arguments gives error

### ISSUE THREAD

**Issue by rohithill** [srbcheema1/medipack#8]
![screenshot from 2018-11-05 01-09-09](https://user-images.githubusercontent.com/12372488/47969058-46117480-e098-11e8-8938-f07c9f8b6388.png)

This can be fixed by calling medipack with -h as default. (Though a thorough treatment would be great.)

**Comment by srbcheema1** [comment]
nice catch :)
I have to check the code.

**Comment by srbcheema1** [comment]
@rohithill  I have resolved this issue. please update your medipack version using `python3 -m pip install --upgrade medipack`
