### ISSUE TITLE
Files with spaces in their names are not detected

### ISSUE THREAD

**Issue by rohithill** [srbcheema1/medipack#9]
Version==2.0.1
OS Ubuntu 18.04.1
![screenshot from 2018-11-16 19-08-04](https://user-images.githubusercontent.com/12372488/48624666-05d4bf00-e9d3-11e8-955e-9951b18f4744.png)

**Comment by eirenik0** [comment]
Same issue here. @srbcheema1 do you have will to implement a fix for this issue?

**Comment by srbcheema1** [comment]
@skhalymon Yeah, I will fix this issue

**Comment by srbcheema1** [comment]
@skhalymon @rohithill I have updated medipack it works fine with version 2.0.4 or above
Please update it and check if it works
